apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: "{{  .Chart.Name }}-selector"
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
        version: "current"
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 20
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: PORT
            value: "{{ .Values.service.servicePort }}"
          - name: APPLICATION_NAME
            value: "{{ .Release.Name }}"
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.kafka.brokersConfigMap }}"
                key: brokers
          - name: KAFKA_SHIP_TOPIC_NAME
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.kafka.topicsConfigMap }}"
                key: bluewaterShipTopic
          - name: KAFKA_CONTAINER_TOPIC_NAME
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.kafka.topicsConfigMap }}"
                key: bluewaterContainerTopic
          - name: KAFKA_BW_PROBLEM_TOPIC_NAME
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.kafka.topicsConfigMap }}"
                key: bluewaterProblemTopic
          {{- if .Values.eventstreams.enabled }}
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.eventstreams.apikeyConfigMap }}"
                key: binding
          {{- end }}
          {{- if .Values.eventstreams.truststoreRequired }}
          - name: TRUSTSTORE_ENABLED
            value: "{{ .Values.eventstreams.truststoreRequired }}"
          - name: TRUSTSTORE_PWD
            value: "{{ .Values.eventstreams.truststorePassword }}"
          - name: TRUSTSTORE_PATH
            value: "{{ .Values.eventstreams.truststorePath }}/{{ .Values.eventstreams.truststoreFile }}"
          {{- end }}
        {{- if .Values.eventstreams.truststoreRequired }}
        volumeMounts:
          - mountPath: "{{ .Values.eventstreams.truststorePath }}"
            name: eventstreams-truststore
            readOnly: true
        {{- end }}
      {{- if .Values.eventstreams.truststoreRequired }}
      volumes:
        - name: eventstreams-truststore
          secret:
            secretName: "{{ .Values.eventstreams.truststoreSecret }}"
      {{- end }}
